### ISSUE TITLE
Difficultés à installer openveo-core

### ISSUE THREAD

**Issue by dspape** [veo-labs/openveo-core#8]
Bonjour,
En suivant la documentation, j'ai installé les pré-réquis: node v8.9.4, npm v5.6.0, mongo v3.4.24
J'ai importé le dossier openveo-core.
les resultats des commandes npm install et node server
En faisant http://localhost:3000  je ne pas accès à l'interface
Qu'est-ce que j'ai raté?

![node](https://user-images.githubusercontent.com/68599892/88655111-359ff980-d0c6-11ea-9588-e1f459614594.png)

**Comment by maxime-beguin** [comment]
Bonjour,

OpenVeo doit être lancé en environnement de production comme indiqué dans la documentation dans la partie "[production](http://veo-labs.github.io/openveo-core/9.0.1/production/)".

**Comment by dspape** [comment]
Bonjour Maxime,
Merci pour votre réponse, dois-je ajouter les lignes dans le fichier server.js?
Comprenez que je ne pas fais ces genres opération auparavant. Je voulais découvrir la solution de openveo.

**Comment by maxime-beguin** [comment]
Non le fichier `server.js` ne doit pas être modifié.
Il s'agit de `NODE_ENV=production node server.js` au lieu de `node server.js`.

**Comment by dspape** [comment]
J'obtiens le même résultat Maxime

![node](https://user-images.githubusercontent.com/68599892/88659897-b3b3ce80-d0cd-11ea-952f-cfb368c3c481.png)

**Comment by dspape** [comment]
localhost n'est pas reconnu mais avec l'adresse IP ça fonctionne
Merci pour votre aide.
Si je rencontre des difficultés, je vous reviendrai.

Merci

**Comment by dspape** [comment]
Bonjour Maxime
Après plusieurs installations et recherche je me retrouve toujours sur cette page. 
Avez-vous svp une idée j'ai ça?
Merci d'avance pour votre aide.
![login](https://user-images.githubusercontent.com/68599892/89520804-54914080-d7d6-11ea-9889-51cf4ddc9788.png)

**Comment by dspape** [comment]
En exécutant la commande:  node server.js 
J'ai l'image jointe
![log](https://user-images.githubusercontent.com/68599892/89554871-51fb0f00-d807-11ea-9da4-c133d4f35b05.png)
.

**Comment by dspape** [comment]
Bonjour, quelqu'un a-t-il s'il vous plait rencontrer ce problème?
